swagger: "2.0"
info:
  description: "API for AI feedback Coach - AD440 Winter 2022"
  version: "1.0"
  title: "AI feedback Coach API"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
paths:

  /feedback:
    post:
      tags:
      - "feedback"
      summary: "Add feedback to Database"
      description: "Add feedback to database"
      operationId: "addFeedback"
      consumes:
      - "application/json"
      produces:
      - "integer"
      parameters:
      - in: "body"
        name: "body"
        description: "feedback"
        required: true
        schema:
          $ref: "#/definitions/Feedback"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/AIFeedback"                   
        "400":
          description: "Bad Request"     
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
    get:
      tags:
      - "feedback"
      summary: "Invalid Operation"
      description: "Invalid Operation, cannot use GET request"
      responses:
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "405":
          description: "Method Not Allowed" 
    patch:
      tags:
      - "feedback"
      summary: "Invalid Operation"
      description: "Invalid Operation, cannot use PATCH request"
      responses:
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "405":
          description: "Method Not Allowed" 
    delete:
      tags:
      - "feedback"
      summary: "Invalid Operation"
      description: "Invalid Operation, cannot use DELETE request"
      responses:
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "405":
          description: "Method Not Allowed" 
          
definitions:
  Feedback:
    type: "object"
    properties:
      feedback:
        type: "string"
        description: "Feedback"
        example: "This is a good feedback"

  AIFeedback:
    type: "object"
    properties:
      feedback:
        type: "string"
        description: "Feedback"
        example: "This is a good feedback"
      isQuestion: 
        type: "boolean"
        description: "Feedback type"
        example: "true"
      isQuestionConfidence:
        type: "number"
        format: "float"
        description: "Confidence of the feedback"
        example: "0.8"
      isSentiment:
        type: "string"
        description: "Sentiment type"
        example: "Is the sentiment good"
      isSentimentConfidence:
        type: "number"
        format: "float"
        description: "Confidence of the sentiment"
        example: "0.6"
      isEmotion: 
        type: "string"
        description: "Emotion type"
        example: "Is the emotion good"
      isEmotionConfidence:
        type: "number"
        format: "float"
        description: "Confidence of the emotion"
        example: "0.7"
      positiveRating:
        type: "number"
        format: "float"
        description: "Positive rating"
        example: "0.4"
      negativeRating:
        type: "number"
        format: "float" 
        description: "Negative rating"
        example: "0.5"
      neutralRating:
        type: "number"
        format: "float"
        description: "Neutral rating"
        example: "0.5"