swagger: "2.0"
info:
  description: "This is the API for AI feedback Coach - AD440 Winter 2022"
  version: "1.0"
  title: "AI feedback Coach API"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "unknown"
basePath: "/"
paths:

  /feedback:
    post:
      tags:
      - "feedback"
      summary: "Add feedback to Database"
      description: "Add feedback to database"
      operationId: "addFeedback"
      consumes:
      - "application/json"
      produces:
      - "integer"
      parameters:
      - in: "body"
        name: "body"
        description: "input feedback"
        required: true
        schema:
          $ref: "#/definitions/Student"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"     
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
    get:
      tags:
      - "feedback"
      summary: "Get AI feedback"
      description: "Get AI feedback from the API"
      operationId: "getFeedback"
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "input feedback"
        required: true
        schema:
          type: "string"
      responses: 
        "200":
          description: "OK"
          schema:
            type: "string"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
    patch:
      tags:
      - "feedback"
      summary: "Invalid Operation"
      description: "Invalid Operation, cannot update feedback"
      responses:
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "405":
          description: "Method Not Allowed" 
    delete:
      tags:
      - "feedback"
      summary: "Invalid Operation"
      description: "Invalid Operation, cannot delete feedback"
      responses:
        "401":
          description: "Unauthorized" 
        "403":
          description: "Forbidden"
        "405":
          description: "Method Not Allowed" 
          
definitions:
  Student:
    type: "object"
    properties:
      comments:
        type: "array"
        items: {type: "string"}