name: Deploy ping response script to lambda
on:
  push:
    branches:
      - "issue#23_jsk_create-github-action"
      - "development"
    paths:
      - "backend/lambda/simplePing/index.js"
jobs:
  job1:
    deploy_lambda:
      name: build and deploy lambda
      strategy:
        matrix:
          node-version: [14.x]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout GitHub repo
          uses: actions/checkout@v2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-west-2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - name: npm install and build
          run: |
            npm ci
            npm run build --if-present
          env:
            CI: true

        - name: zip
          uses: montudor/action-zip@v0.1.0
          with:
            args: zip -qq -r ./bundle.zip ./

        - name: default deploy
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: us-west-2
            function_name: simplePing
            zip_file: bundle.zip
  job2:
    name: build frontend post script
    runs-on: ubuntu-latest
    needs: job1
